# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Starbucks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Starbucks
  pod 'SwiftLint', '~> 0.47.1'
  pod 'SwiftFormat/CLI', '~> 0.49.8'

end
